use_frameworks!

platform :ios, '12.1'

target 'AssertionNotifier_Example' do
  pod 'AssertionNotifier', :path => '../'

  target 'AssertionNotifier_Tests' do
    inherit! :search_paths

    
  end
end
