# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode12.5
language: swift
# cache: cocoapods
# podfile: Example/Podfile
# before_install:
- gem install cocoapods # Since Travis is not always on latest version
- pod --version

script:
- cd Example/
- pod install --repo-update
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/AssertionNotifier.xcworkspace -scheme AssertionNotifier-Example -sdk iphonesimulator14.5 ONLY_ACTIVE_ARCH=NO | xcpretty